/*
 * humanizer-local.js — reescrita sem IA, sem crédito, sem rede.
 *
 * A reescrita pelo modelo é mais profunda: ela renomeia, reorganiza e reescreve. Mas boa
 * parte do que denuncia código gerado é mecânica — caractere invisível, assinatura de
 * ferramenta, comentário que repete a linha de baixo, banner decorativo, JSDoc de molde,
 * espaçamento uniforme demais. Isso dá para tirar com regra determinística.
 *
 * A regra que vale acima de todas: NÃO MUDAR O COMPORTAMENTO. Nada aqui toca em código
 * executável nem no conteúdo de uma string. Só comentário, espaço em branco e caractere
 * invisível. Se uma transformação não couber nessa garantia, ela não entra — vira
 * sugestão para a pessoa decidir, não mudança automática.
 *
 * O que isto NÃO faz, e por quê:
 *   - renomear identificador genérico (data, result, processData): exige saber o escopo.
 *     Sem analisar a sintaxe de verdade, um replace de texto quebra código.
 *   - desfazer abstração prematura, reescrever erro cerimonial, variar estrutura: são
 *     julgamentos sobre intenção, não padrões de texto.
 * Essas continuam sendo trabalho do modelo. O relatório diz quanto sobrou para ele.
 */

/** Caracteres que não deveriam estar em código-fonte escrito à mão. */
const INVISIVEIS_LOCAIS = [
  { re: /​/g, nome: 'espaço de largura zero' },
  { re: /‌/g, nome: 'não-juntador de largura zero' },
  { re: /‍/g, nome: 'juntador de largura zero' },
  { re: /⁠/g, nome: 'juntador de palavra' },
  { re: /﻿/g, nome: 'marca de ordem de byte no meio do texto' },
  { re: /­/g, nome: 'hífen opcional' },
  { re: / /g, nome: 'espaço inquebrável', troca: ' ' },
];

/** Tipografia que editor de código não produz, mas processador de texto sim. */
const TIPOGRAFIA = [
  { re: /—/g, troca: '--', nome: 'travessão' },
  { re: /–/g, troca: '-',  nome: 'traço' },
  { re: /[‘’]/g, troca: "'", nome: 'aspa curva simples' },
  { re: /[“”]/g, troca: '"', nome: 'aspa curva dupla' },
  { re: /…/g, troca: '...', nome: 'reticências de um caractere' },
];

/** Assinaturas que entregam a ferramenta na hora. */
const ASSINATURAS = [
  /^\s*(?:\/\/|#|\*)?\s*Co-Authored-By:\s*Claude.*$/gim,
  /^\s*(?:\/\/|#|\*)?\s*(?:🤖\s*)?Generated with \[?Claude Code\]?.*$/gim,
  /^\s*(?:\/\/|#|\*)?\s*Generated by (?:ChatGPT|Copilot|Claude|GPT-\d).*$/gim,
];

/** Comentário de linha, por linguagem. */
function prefixoDeComentario(lang) {
  return /python|ruby|shell|bash|yaml|toml|powershell|^r$/i.test(String(lang || ''))
    ? '#' : '//';
}

/**
 * Marca quais linhas são comentário.
 *
 * Não é um analisador de sintaxe — é uma varredura linha a linha, que basta porque só
 * removemos linhas inteiras de comentário. Uma linha com código e comentário no fim não
 * é tocada: separar os dois com segurança exigiria entender strings, e o risco não
 * compensa o ganho.
 */
function mapearComentarios(linhas, lang) {
  const pfx = prefixoDeComentario(lang);
  const tipos = new Array(linhas.length).fill('codigo');
  let emBloco = false;

  linhas.forEach((raw, i) => {
    const l = raw.trim();
    if (emBloco) {
      tipos[i] = 'bloco';
      if (/\*\/|"""|'''/.test(l)) emBloco = false;
      return;
    }
    if (!l) { tipos[i] = 'vazia'; return; }
    if (l.startsWith('/*') || /^(?:"""|''')/.test(l)) {
      tipos[i] = 'bloco';
      if (!/\*\/|(?:"""|''').*(?:"""|''')/.test(l)) emBloco = true;
      return;
    }
    if (l.startsWith(pfx) || (pfx === '//' && l.startsWith('*'))) tipos[i] = 'comentario';
  });
  return tipos;
}

/** Tira pontuação e artigos para comparar um comentário com o código que ele descreve. */
function essencia(texto) {
  return String(texto)
    .toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(p => p && !['o','a','os','as','um','uma','de','do','da','e','que','the','a',
                        'an','of','to','for','this','that','is','are','we','it'].includes(p))
    .join(' ')
    .trim();
}

/**
 * Ponte português↔inglês para as palavras que aparecem em comentário de uma linha.
 *
 * Código brasileiro quase sempre mistura: identificador em inglês, comentário em
 * português. Sem isto, "// retorna o resultado" sobre `return result` passaria batido —
 * e é justamente o comentário vazio mais comum por aqui.
 */
const PONTE = {
  retorna: 'return', retornar: 'return', devolve: 'return',
  resultado: 'result', resultados: 'result',
  dados: 'data', dado: 'data',
  valor: 'value', valores: 'value',
  cria: 'create', criar: 'create', gera: 'create',
  busca: 'get', buscar: 'get', pega: 'get', obtem: 'get',
  define: 'set', definir: 'set',
  lista: 'list', listar: 'list',
  conta: 'count', contar: 'count', total: 'total',
  nome: 'name', indice: 'index', chave: 'key',
  salva: 'save', salvar: 'save', apaga: 'delete', remover: 'remove', remove: 'remove',
  atualiza: 'update', atualizar: 'update',
  valida: 'valid', validar: 'valid',
  novo: 'new', nova: 'new', item: 'item', itens: 'item',
  erro: 'error', mensagem: 'message',
  usuario: 'user', cliente: 'client', pedido: 'order', produto: 'product',
};

/** Normaliza uma palavra para comparar comentário com código. */
function raiz(p) {
  const traduzida = PONTE[p] || p;
  // "results" e "result", "dados" e "data": compara pelo começo
  return traduzida.replace(/(?:s|es)$/, '');
}

/** Um comentário que só repete o que a linha seguinte já diz não informa nada. */
function repeteALinha(comentario, codigo) {
  const c = essencia(comentario.replace(/^\s*(?:\/\/+|#+|\*+)\s*/, ''));
  if (!c || c.split(' ').length > 6) return false;   // comentário longo costuma explicar
  const alvo = essencia(codigo).split(' ').map(raiz);
  if (!alvo.length) return false;
  const palavras = c.split(' ').map(raiz).filter(Boolean);
  // toda palavra do comentário reaparece no código: é paráfrase, não explicação
  // O casamento por prefixo só vale para palavra com corpo: com 1 ou 2 letras, quase
  // tudo "contém" quase tudo, e aí o apagador começa a comer comentário bom.
  return palavras.length >= 1 && palavras.every(p =>
    alvo.some(a => a === p || (p.length >= 3 && a.length >= 3
                               && (a.includes(p) || p.includes(a)))));
}

/** Banner decorativo: uma régua de =, - ou * que só ocupa espaço. */
function ehBannerDecorativo(linha) {
  const l = linha.trim().replace(/^(?:\/\/+|#+|\*+)\s*/, '');
  return /^[=\-*_~]{6,}$/.test(l);
}

/** JSDoc/docstring cujas descrições não dizem nada além do nome do parâmetro. */
function ehDocstringDeMolde(bloco) {
  const linhas = bloco.map(l => l.trim().replace(/^\*+\s?/, ''));
  const tags = linhas.filter(l => /^@(param|returns?|arg)/.test(l));
  if (!tags.length) return false;
  const vazias = tags.filter(l => {
    const desc = l.replace(/^@\w+\s*(?:\{[^}]*\}\s*)?(?:\w+\s*)?-?\s*/, '').trim();
    if (!desc) return true;
    // "The data.", "O resultado.", "The result object." — descrição que repete o nome
    return /^(?:the|o|a|os|as|um|uma)?\s*[\w\s]{0,24}\.?$/i.test(desc)
      && essencia(desc).split(' ').length <= 3;
  });
  return vazias.length === tags.length;
}

/**
 * Reescreve o que dá para reescrever sem modelo.
 *
 * @param {string} conteudo  o arquivo inteiro
 * @param {string} lang      a linguagem, para saber o prefixo de comentário
 * @param {{intensidade?: 'conservadora'|'padrao'}} opts
 * @returns {{codigo: string, mudancas: Array, naoFeito: Array}}
 */
function reescritaLocal(conteudo, lang, opts = {}) {
  const intensidade = opts.intensidade || 'padrao';
  const mudancas = [];
  const conta = (que, onde) => {
    const achado = mudancas.find(m => m.que === que);
    if (achado) { achado.n++; if (onde && achado.onde.length < 4) achado.onde.push(onde); }
    else mudancas.push({ que, n: 1, onde: onde ? [onde] : [] });
  };

  let texto = String(conteudo || '');

  // ── 1. caracteres invisíveis ───────────────────────────────────────────────
  INVISIVEIS_LOCAIS.forEach(({ re, nome, troca }) => {
    const n = (texto.match(re) || []).length;
    if (n) { texto = texto.replace(re, troca || ''); conta('removeu ' + nome, null);
             mudancas[mudancas.length - 1].n = n; }
  });

  // ── 2. assinaturas de ferramenta ───────────────────────────────────────────
  ASSINATURAS.forEach(re => {
    const achados = texto.match(re);
    if (achados) {
      texto = texto.replace(re, '');
      achados.forEach(() => conta('removeu assinatura de ferramenta', null));
    }
  });

  let linhas = texto.split(/\r?\n/);
  let tipos = mapearComentarios(linhas, lang);

  // ── 3. tipografia, só dentro de comentário ─────────────────────────────────
  // Em código ou string, trocar aspa curva por reta muda o programa. Em comentário, não.
  linhas = linhas.map((l, i) => {
    if (tipos[i] !== 'comentario' && tipos[i] !== 'bloco') return l;
    let saida = l;
    TIPOGRAFIA.forEach(({ re, troca, nome }) => {
      if (re.test(saida)) { saida = saida.replace(re, troca); conta('trocou ' + nome + ' em comentário', i + 1); }
    });
    return saida;
  });

  // ── 4. banners decorativos ─────────────────────────────────────────────────
  const manter = new Array(linhas.length).fill(true);
  linhas.forEach((l, i) => {
    if ((tipos[i] === 'comentario' || tipos[i] === 'bloco') && ehBannerDecorativo(l)) {
      manter[i] = false;
      conta('removeu régua decorativa', i + 1);
    }
  });

  // ── 5. comentário que repete a linha de baixo ──────────────────────────────
  linhas.forEach((l, i) => {
    if (tipos[i] !== 'comentario' || !manter[i]) return;
    // a próxima linha de código, pulando vazias
    let j = i + 1;
    while (j < linhas.length && tipos[j] === 'vazia') j++;
    if (j >= linhas.length || tipos[j] !== 'codigo') return;
    if (repeteALinha(l, linhas[j])) {
      manter[i] = false;
      conta('removeu comentário que repetia o código', i + 1);
    }
  });

  // ── 6. docstring de molde ──────────────────────────────────────────────────
  if (intensidade !== 'conservadora') {
    let i = 0;
    while (i < linhas.length) {
      if (tipos[i] === 'bloco' && /\/\*\*|"""|'''/.test(linhas[i])) {
        let fim = i;
        while (fim < linhas.length && tipos[fim] === 'bloco') fim++;
        const bloco = linhas.slice(i, fim);
        if (bloco.length >= 3 && ehDocstringDeMolde(bloco)) {
          for (let k = i; k < fim; k++) manter[k] = false;
          conta('removeu docstring de molde', i + 1);
        }
        i = fim;
      } else i++;
    }
  }

  linhas = linhas.filter((_, i) => manter[i]);

  // ── 7. espaço em branco ────────────────────────────────────────────────────
  const comEspacoAtras = linhas.filter(l => /[ \t]+$/.test(l)).length;
  if (comEspacoAtras) {
    linhas = linhas.map(l => l.replace(/[ \t]+$/, ''));
    conta('tirou espaço no fim da linha', null);
    mudancas[mudancas.length - 1].n = comEspacoAtras;
  }

  const antes = linhas.length;
  const saida = [];
  let vazias = 0;
  linhas.forEach(l => {
    if (!l.trim()) { vazias++; if (vazias > 1) return; } else vazias = 0;
    saida.push(l);
  });
  if (saida.length < antes) {
    conta('juntou linhas em branco seguidas', null);
    mudancas[mudancas.length - 1].n = antes - saida.length;
  }

  // tira linhas em branco do começo e do fim, e garante uma quebra final
  while (saida.length && !saida[0].trim()) saida.shift();
  while (saida.length && !saida[saida.length - 1].trim()) saida.pop();

  // ── o que ficou para o modelo ──────────────────────────────────────────────
  const naoFeito = [
    'renomear identificador genérico (data, result, processData) — exige entender o escopo',
    'desfazer abstração criada sem necessidade',
    'variar a estrutura repetitiva entre funções',
    'reescrever tratamento de erro cerimonial',
  ];

  return {
    codigo: saida.join('\n') + '\n',
    mudancas: mudancas.filter(m => m.n > 0),
    naoFeito,
  };
}
